### PR TITLE
Remove unneeded sphinxcontrib dependency (which is not in conda-forge)

### PR DESCRIPTION
**Pull request by erykoff**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

The `sphinxcontrib` run dependency is not necessary, and this package isn't available on conda-forge so it's pulling in a package from defaults that turns out to be one blank `__init__.py` file.

### CODE REVIEW

**Comment by erykoff** [comment]
@conda-forge/sphinxcontrib-doxylink This is ready.

**Comment by erykoff** [comment]
@duncanmmacleod This needs a review, and I think that you haven't been pinged on other bot PRs because only now did the rerender add a CODEOWNERS.  Thanks!

**Comment by isuruf** [comment]
That blank `__init__.py` is important and is not unnecessary

**Comment by erykoff** [comment]
None of the other `sphinxcontrib-` packages require it.  Why only this one?

**Comment by erykoff** [comment]
Alternatively, we need to have `sphinxcontrib` in `conda-forge`.

**Comment by erykoff** [comment]
Following up, namespace packages haven't been needed since py3.3, and this requires py3.4 or later so I think is okay. https://www.python.org/dev/peps/pep-0420/

**Comment by isuruf** [comment]
Sounds good to me

**Review by isuruf — APPROVED** [review]

**Comment by erykoff** [comment]
@isuruf this is ready

**Pull request merged**
